import { OmniField } from "../omni-field.interface";

export const omnifield:OmniField[]=[
  {
    "sl": 1,
    "name": "description",
    "type": "campaign",
    "description": "User generated description of the campaign",
    "route": "admin_campaign_general_ajax"
  },
  {
    "sl": 2,
    "name": "id",
    "type": "campaign",
    "description": "This is the unique numerical identifier generated by the system that references this specific campaign.",
    "route": "admin_campaign_general_ajax"
  },
  {
    "sl": 3,
    "name": "name",
    "type": "campaign",
    "description": "User generated name for campaign.",
    "route": "admin_campaign_general_ajax"
  },
  {
    "sl": 4,
    "name": "caller_id",
    "type": "campaign",
    "description": "This is the default Caller ID shown if no list or areacode based Caller ID features are enabled",
    "route": "admin_campaign_general_ajax"
  }
]